export const constants = {
  title: 'Take Note',
  subtitle: 'Captura todo lo que quieres manterner siempre a la mano.',
  google: 'google',
  twitter: 'twitter',
  github: 'github',
  createNote: 'Creart nota',
  noteList: 'Lista de notas',
  noNotesFound: 'No se encontraron notas',
  writeNote: 'Escribe una nota',
  takingNote: '¡Empecemos a tomar nota!',
  edit: 'Editar',
  delete: 'Eliminar',
  cancel: 'Cancelar',
  deleteNote: 'Eliminar nota',
  sureToDelete: 'Estás seguro que quieres eliminar',
};
