export const constants = {
  title: 'Take Note',
  subtitle: 'Captura todo lo que quieres manterner siempre a la mano.',
  google: 'google',
  twitter: 'twitter',
  github: 'github',
  createNote: 'Creart nota',
  noteList: 'Lista de notas',
  noNotesFound: 'No se encontraron notas',
  writeNote: 'Escribe una nota',
  takingNote: '¡Empecemos a tomar nota!',
  edit: 'Editar',
  delete: 'Eliminar',
  cancel: 'Cancelar',
  accept: 'Aceptar',
  save: 'Guardar',
  deleteNote: 'Eliminar nota',
  sureToDelete: 'Estás seguro que quieres eliminar',
  createFolder: 'Crear carpeta',
  folderNameError: 'Debe tener minimo 3 caracteres o ya existe',
  newFolder: 'newFolder',
  alertError: 'error',
  alertSuccess: 'success',
  saveNoteSuccess: '¡Nota guardada!',
  userNotesError: 'Ocurrió un error, intente más tarde',
  saveNoteError: 'No se guardo la nota correctamente',
  getNotesError: 'No se pudo obtener las notas',
  updateNoteSuccess: '¡Se actualizó la nota!',
  updateNoteError: 'No se pudo actualizar la nota',
  deleteNoteError: 'No se pudo eliminar la nota',
  searchNoteError: 'No se pudo hacer la búsqueda',
};
