export const types = {
  authLogin: 'AUTH_LOGIN',
  authLogout: 'AUTH_LOGOUT',
  createNote: 'CREATE_NOTE',
  saveNote: 'SAVE_NOTE',
  activateNote: 'ACTIVATE_NOTE',
  activateFolder: 'ACTIVATE_FOLDER',
  folders: 'ALL_FOLDERS',
  notes: 'FOLDER_NOTES',
  deleteNote: 'DELETE_NOTE',
  cancelNote: 'CANCEL_NOTE',
  logoutNote: 'LOGOUST_NOTE',
  searchNote: 'SEARCH_NOTE',
  showAlert: 'SHOW_ALERT',
  hideAlert: 'HIDE_ALERT',
  observableNext: 'OBSERVABLE_NEXT',
  showLoader: 'SHOW_LOADER',
  hideLoader: 'HIDE_LOADER',
};
